[2023-09-22T16:52:17.261+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-09-22T16:52:17.547+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_taskflow_api_v02.get_age__1 scheduled__2021-11-15T00:00:00+00:00 [queued]>
[2023-09-22T16:52:17.580+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_taskflow_api_v02.get_age__1 scheduled__2021-11-15T00:00:00+00:00 [queued]>
[2023-09-22T16:52:17.583+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 6
[2023-09-22T16:52:17.624+0000] {taskinstance.py:1350} INFO - Executing <Task(_PythonDecoratedOperator): get_age__1> on 2021-11-15 00:00:00+00:00
[2023-09-22T16:52:17.630+0000] {standard_task_runner.py:57} INFO - Started process 496 to run task
[2023-09-22T16:52:17.640+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_taskflow_api_v02', 'get_age__1', 'scheduled__2021-11-15T00:00:00+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/test2.py', '--cfg-path', '/tmp/tmpoe37w55q']
[2023-09-22T16:52:17.649+0000] {standard_task_runner.py:85} INFO - Job 111: Subtask get_age__1
[2023-09-22T16:52:17.681+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.9/site-packages/***/settings.py:188 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-09-22T16:52:17.782+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_with_taskflow_api_v02.get_age__1 scheduled__2021-11-15T00:00:00+00:00 [running]> on host 75cee4990e54
[2023-09-22T16:52:17.830+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-09-22T16:52:19.498+0000] {local_task_job_runner.py:232} INFO - Task exited with return code Negsignal.SIGKILL
[2023-09-22T16:52:20.675+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
